export const actionTypes = {
  SET_EVENT_DATA: 'SET_EVENT_DATA',
  SET_EVENT_CATEGORY_DATA: 'SET_EVENT_CATEGORY_DATA',

  SET_BUSINESS_CATEGORY_DATA: 'SET_BUSINESS_CATEGORY_DATA',
  SET_BUSINESS_DATA: 'SET_BUSINESS_DATA',

  TOGGLE_ONLY_MODAL: 'TOGGLE_ONLY_MODAL',

  TOGGLE_USER_MODAL: 'TOGGLE_USER_MODAL',
  OPEN_USER_MODAL: 'OPEN_USER_MODAL',
  CLOSE_USER_MODAL: 'CLOSE_USER_MODAL',

  OPEN_VENUE_MODAL: 'OPEN_VENUE_MODAL',
  CLOSE_VENUE_MODAL: 'CLOSE_VENUE_MODAL',

  OPEN_USER_ADD_VENUE: 'OPEN_USER_ADD_VENUE',
  CLOSE_USER_ADD_VENUE: 'CLOSE_USER_ADD_VENUE',

  SET_LOGIN_MODAL_TYPE: 'SET_LOGIN_MODAL_TYPE',
  SET_LOGIN_MODAL_VISBILITY: 'SET_LOGIN_MODAL_VISBILITY',

  OPEN_VENUE_MANAGER_MODAL: 'OPEN_VENUE_MANAGER_MODAL',
  CLOSE_VENUE_MANAGER_MODAL: 'CLOSE_VENUE_MANAGER_MODAL',
  
  OPEN_USER_EDIT_VENUE_MODAL: "OPEN_USER_EDIT_VENUE_MODAL",
  CLOSE_USER_EDIT_VENUE_MODAL: "CLOSE_USER_EDIT_VENUE_MODAL",

  SET_COPIED: 'SET_COPIED',

  SET_SELECTED_FILTER: 'SET_SELECTED_FILTER',

  SET_LOADING: "SET_LOADING",
  CLEAR_LOADING: "CLEAR_LOADING",

  SET_SELECTED_VENUE: 'SET_SELECTED_VENUE',
  RESET_SELECTED_VENUE: 'RESET_SELECTED_VENUE',

  SET_SELECTED_ITEM: 'SET_SELECTED_ITEM',
  RESET_SELECTED_ITEM: 'RESET_SELECTED_ITEM',

  DELETE_BUSINESS_BY_ID: 'DELETE_BUSINESS_BY_ID',
  DELETE_EVENT_BY_ID: 'DELETE_EVENT_BY_ID',

  DELETE_ENTITY_SUCCESS: "DELETE_ENTITY_SUCCESS",
  DELETE_ENTITY_FAILURE: "DELETE_ENTITY_FAILURE",
  
  CREATE_ENTITY_FAILURE: "CREATE_ENTITY_FAILURE",
  CREATE_ENTITY_SUCCESS: "CREATE_ENTITY_SUCCESS",
};